---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: team1
  namespace: group-0001
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/app-team-1-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team1
  namespace: group-0001
spec:
  serviceAccountName: tenant-flux-reconciler
  interval: 10m0s
  path: ./clusters/flux-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: team1

---

apiVersion: v1
kind: Namespace
metadata:
  name: tenant-apps